# Ejercicio en clase: 29/07/2019

In [1]:
import numpy as np
from sklearn.preprocessing import PolynomialFeatures

In [2]:
x = np.random.randint(10,size=(1,1))

In [3]:
x

array([[0]])

In [4]:
poly = PolynomialFeatures(2)
print(poly.fit_transform(x))
print('La complejidad del polinomio aumento a: ', len(poly.fit_transform(x)[0]))

[[1. 0. 0.]]
La complejidad del polinomio aumento a:  3


In [5]:
x = np.random.randint(10,size=(1,2))
x

array([[5, 0]])

In [6]:
print(poly.fit_transform(x))
print('La complejidad del polinomio aumento a: ', len(poly.fit_transform(x)[0]))

[[ 1.  5.  0. 25.  0.  0.]]
La complejidad del polinomio aumento a:  6


In [7]:
x = np.random.randint(1,10,size=(1,3))
x

array([[5, 1, 6]])

In [8]:
print(poly.fit_transform(x))
print('La complejidad del polinomio aumento a: ', len(poly.fit_transform(x)[0]))

[[ 1.  5.  1.  6. 25.  5. 30.  1.  6. 36.]]
La complejidad del polinomio aumento a:  10


### Comentarios:

La funcion *PolynomialFeatures* nos es util a para generar polinomios de grado 2 considerando, los coeficientes de las variables de dicho polinomio.  Ademas, nos brinda la interaccion de los polinomios entre si (es decir, la combinacion de los distintos polinomios. Esto puede ser una herramienta muy util al momento de realizar Feature Engineering, **con esta herramienta encontramos la lista de las posible features, y al momento de entrenar el modelo, en base a los pesos que nos genere, podemos ver cuales son mas significativas y poderlas utilizar**

**Sin embargo, el costo computacional aumenta exponencialmente, por lo que es necesario evaluar los casos en los que sea necesario obtener las posibles combinaciones de la variable**