## Ejercicio practico: multiplicacion y aritmetica matricial.

**Ejercicio aplicado en DS**
Se tiene una red neuronal sencilla(y simplificada) como la de la siguiente imagen:
<img src="https://www.oreilly.com/library/view/practical-convolutional-neural/9781788392303/assets/246151fb-7893-448d-b9bb-7a87b387a24b.png">

Donde:
* INPUT LAYER: un vector X de tamaño = 2 que representa los datos de entrada
* HIDDEN_LAYER :capa oculta con 2 neuronas definidas por los vectores:
    * HL1 = [0.25,0.37]
    * HL2 = [-8,14]
* OUTPUT_LAYER = capa de salida definida por el vector [4,9]

Crear una funcion neural_network(X) para calcular:
* Calcule la salida de cada neurona en la capa intermedia aplicada a la capa de entrada.
* Use el resultado del paso anterior como entrada para la neurona en la capa de salida

Utilizando multiplicacion de matrices se debe calcular para cada fila de la matriz de entrada X el valor de las neuronas de la capa intermedia, esto producira una nueva matriz con el mismo numero de filas que X y 2 columnas(1 para cada neurona) , a  los valores de esta matriz se les debe aplicar la funcion "sigmoid"(descrita a continuacion) para limitarlos al intervalo de 0 a 1, esto produce una matriz del mismo tamanio pero con valores entre 0 a 1, esta matriz se multiplica matricialmente por la matriz que representa los pesos de la capa de salida  y este proceso produce un nuevo tensor al cual se debe aplicar nuevamente la funcion sigmoid. El resultado debe ser un tensor con el mismo numero de filas que la matriz X y una sola columna(una prediccion para cada fila de X

<img src="https://cdn-images-1.medium.com/max/1600/1*Xu7B5y9gp0iL5ooBj7LtWw.png">

In [54]:
import numpy as np
def sigmoid(x): #convertir los valores de x al rango de 0 a 1
    
    return 1/(1+np.exp(-x))

In [55]:
H1_W = np.array([[0.25,-8],
                 [0.37,14]])
OL_W = np.array([[4],[9]])

X =  np.array([[0.1,0.2],
               [1,2]])

H1 = np.matmul(X,H1_W)

H1 = sigmoid(H1)  # funcion de activacion: convertir a valores en el intervalo de 0 a 1
OL = np.matmul(H1,OL_W)
OL = sigmoid(OL)  # funcion de activacion: convertir a valores en el intervalo de 0 a 1

print(OL)

[[0.99995577]
 [0.99999332]]


In [56]:
def neural_network(X):
    H1_W = np.array([[0.25,-8],
                     [0.37,14]])
    OL_W = np.array([[4],[9]])
    H1 = np.matmul(X,H1_W)
    print("El resultado de la primera neurona es: \n", np.array([[H1[0][0]],[H1[1][0]]]))
    print("El resultado de la segunda neurona es: \n", np.array([[H1[0][1]],[H1[1][1]]]))
    H1 = sigmoid(H1)
    OL = np.matmul(H1,OL_W)
    OL = sigmoid(OL) 
    return OL

X =  np.array([[0.1,0.2],
               [1,2]])
print("\nEl resultado de la red neuronal para ambos sets de datos es: \n", neural_network(X))

El resultado de la primera neurona es: 
 [[0.099]
 [0.99 ]]
El resultado de la segunda neurona es: 
 [[ 2.]
 [20.]]

El resultado de la red neuronal para ambos sets de datos es: 
 [[0.99995577]
 [0.99999332]]


### Ejercicio 

Implementar en una funcion neural_network(X) la red neuronal definida por la siguiente arquitectura:

<img src="http://i.imgur.com/UNlffE1.png">

Podemos validar si fue correctamente implementada si usamos como entrada el vector x=[1,1] . Debemos obtener el resultado mostrado en la imagen.

Una vez tenemos la implementacion correcta, cambiar la funcion de activacion de la capa de salida por la funcion de activacion ReLu(https://en.wikipedia.org/wiki/Rectifier_(neural_networks)):

<img src="https://cdn-images-1.medium.com/max/1600/1*DfMRHwxY1gyyDmrIAd-gjQ.png">

Luego evaluar la red neuronal sobre la matriz de datos X(de manera vectorizada):

In [57]:
#Creacion de la funcion de ReLu

def ReLu(x):
    condList = [x<0, x>=0]
    funcList = [lambda x: 0, lambda x: x]
    final =  np.piecewise(x,condList,funcList) 
    return(final)

In [58]:
print(ReLu(np.array([[-4,0,-200,3,5],[4,6,2,-22,98]]))) #Prueba de la funcion de ReLu para matrices

[[ 0  0  0  3  5]
 [ 4  6  2  0 98]]


In [59]:
def neural_network(X):

    H1_W= np.array([[0.712,0.355,0.268],
                   [0.112,0.855,0.468]])

    OL_W= np.array([[0.116],[0.329], [0.708]])


    HL =np.matmul(X, H1_W)
    HL =sigmoid(HL)

    OL =np.matmul(HL,OL_W)
    OL =ReLu(OL)

    return(OL)
    
testData = np.array([1,1])

print(neural_network(testData))

[0.81275154]


In [60]:
X = np.array([
    [0.1,2],
    [0.3,0.45],
    [5,9],
    [12,6],
    [7,5],
    [0.3,0.8],
    [12,5],
    [100,200],
    [7,8],
    [300,1500]])
print(neural_network(X))

[[0.85897151]
 [0.6748703 ]
 [1.14904686]
 [1.15125178]
 [1.14187076]
 [0.72619803]
 [1.15019715]
 [1.153     ]
 [1.1500904 ]
 [1.153     ]]
