## np.array() VS. np.matrix()

Ambas formas pueden representar tensores de grado 2 (matrices tal como las conocemos en matematicas). Dado que una matriz se puede tomar como una agrupacion de vectores (un tensor de grado dos se puede entenrse como la composicion de dos o mas tensores de grado 1), es posible crear matrices a traves de vectores.

## Analisis inicial

A continuacion se muestran algunas declaraciones de estos objetos:

In [27]:
import numpy as np
vectMat = np.array([[7,5],[11,17]])
vectMat2 = np.array([[5,2],[4,19]])
matF1 = np.matrix([[7,5],[11,17]])
matF2 = np.matrix([[5,2],[4,19]])


print('\nMatriz como utilizando una composicion de vectores\n',vectMat)
print('\nMatriz declarada de forma estandard utilizando np.matrix()\n', matF1)

print('\nTipo del objeto vectMat', type(vectMat))
print('Tipo del objeto matF1', type(matF1))

print('\nRango para el tensor vectMat', vectMat.ndim)
print('Forma para el tensor vectMat', vectMat.shape)
print('\nRango para el tensor matF1', matF1.ndim)
print('Forma para el tensor matF1', matF1.shape)



Matriz como utilizando una composicion de vectores
 [[ 7  5]
 [11 17]]

Matriz declarada de forma estandard utilizando np.matrix()
 [[ 7  5]
 [11 17]]

Tipo del objeto vectMat <class 'numpy.ndarray'>
Tipo del objeto matF1 <class 'numpy.matrixlib.defmatrix.matrix'>

Rango para el tensor vectMat 2
Forma para el tensor vectMat (2, 2)

Rango para el tensor matF1 2
Forma para el tensor matF1 (2, 2)


A primera vista puede decirse que en sus caracteristicas matematicas basicas son practicamente equivalentes. Ambos son tensores de rango 2 y ambos devuelven una tupla con el tamano de la matriz. 

Sin embargo, la diferencia se muestra en el tipo de objeto que representan, siendo el objeto generado con np.array() un objeto de tipo nd.array y el otro un objeto de tipo matrix. Esto conlleva consecuencias fundamentales al momento de aplicar funciones y metodos a los mismos.

Se muestran algunas operaciones basicas comunes entre ambos tipos de estructueras(vectores y matrices)

In [66]:
print('Segunda estructura para realizar las operaciones:\n', matF2)


print('\n\nSuma utilizando objetos tipo np.array \n', vectMat+vectMat2)
print('Suma utilizando objetos tipo np.matrix \n', matF1+matF2)


print('\nResta utilizando objetos tipo np.array \n',  vectMat-vectMat2)
print('Resta utilizando objetos tipo np.matrix \n', matF1-matF2 )

print('\nMultilicacion utilizando objetios tipo np.array()\n', vectMat*vectMat2)
print('Multiplicacion utilizando objetos tipo np.matrix()\n', matF1*matF2)


Segunda estructura para realizar las operaciones:
 [[ 5  2]
 [ 4 19]]


Suma utilizando objetos tipo np.array 
 [[12  7]
 [15 36]]
Suma utilizando objetos tipo np.matrix 
 [[12  7]
 [15 36]]

Resta utilizando objetos tipo np.array 
 [[ 2  3]
 [ 7 -2]]
Resta utilizando objetos tipo np.matrix 
 [[ 2  3]
 [ 7 -2]]

Multilicacion utilizando objetios tipo np.array()
 [[ 35  10]
 [ 44 323]]
Multiplicacion utilizando objetos tipo np.matrix()
 [[ 55 109]
 [123 345]]


Como se puede apreciar, vemos que tanto la suma como la resta tienen el mismo resultado, puesto que matematicamente estan definidas de la misma forma para ambas estructuras, sin embargo, la primera notable diferencia la encontramos en la multiplicacion. Vemos que las estructuras definidas mediante np.matrix respetan las reglas matematicas de esta operacion mientras que las definidas por np.array multiplican elemento por elemento. 

De igual forma, para todas las demas operaciones definidas para las matrices unicamente (matriz inversa, transpuesta, determinante, etc)

Sin embargo, es posible efectuar operaciones con los mismos resultados propias de matrices para objetos tipo np.array() utilizando otro tipo de comandos:


Otra distincion entre np.array() y np.matrix() (y la que supone una ventaja de np.array() sobre np.matrix()) es en cuanto a la creacion de tensores de rango superior, dado que np.array() es en general para estructuras de N  dimensiones mientras que np.matrix es estrictamente (al menos teoria) para estructuras de dos dimensiones.

In [61]:
y = np.array([[[4,5],[8,4]],[[6,3],[5,8]]])
print(y)
print(y.ndim)

[[[4 5]
  [8 4]]

 [[6 3]
  [5 8]]]
3


In [56]:
w = np.matrix([[[4,5],[8,4]],[[6,3],[5,8]]])

ValueError: matrix must be 2-dimensional

Tal como observamos een el tipo de error que nos genera la ultima sentencia, Python nos indica que una instancia del objeto np.matrix() debe ser un arreglo de dos dimensiones.

Como ultimo punto, es posible realizar un typecasting para realizar la conversion de un tipo de objeto a otro. 

In [68]:
print(type(np.asarray(matF1)))
print(type(np.asmatrix(vectMat)))

<class 'numpy.ndarray'>
<class 'numpy.matrixlib.defmatrix.matrix'>
